name: Tests API Postman avec Newman

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  tests-api:
    runs-on: ubuntu-latest

    steps:
      - name: 1 - Recuperation du projet GitHub
        uses: actions/checkout@v4

      - name: 2 - Installation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 3 - Verification de Node.js et npm
        run: |
          node -v
          npm -v

      - name: 4 - Installation de Newman et du reporter HTML
        run: |
          npm install newman newman-reporter-htmlextra --no-save

      - name: 5 - Preparation du dossier des rapports
        run: |
          mkdir -p reports

      - name: 6 - Execution de la collection Postman
        id: newman
        continue-on-error: true
        run: |
          npx newman run Clients.postman_collection.json \
            -e env.postman_environment.json \
            --reporters cli,htmlextra \
            --reporter-htmlextra-export reports/RapportCollectionClients.html

      - name: 7 - Archivage du rapport HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: RapportCollectionClients
          path: reports/RapportCollectionClients.html

      - name: 8 - Envoi du rapport par mail
        if: always()
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.gmail.com
          server_port: 587
          secure: false
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Rapport tests API - GitHub Actions - ${{ job.status }}"
          to: ${{ secrets.MAIL_TO }}
          from: ${{ secrets.MAIL_USERNAME }}
          body: |
            Bonjour,

            Les tests API ont été exécutés automatiquement avec GitHub Actions.

            Repository : ${{ github.repository }}
            Branche : ${{ github.ref_name }}
            Commit : ${{ github.sha }}
            Statut du job : ${{ job.status }}

            Le rapport HTML est joint à ce mail.

            Cordialement,
            Mastene Messouya - GitHub Actions
          attachments: reports/RapportCollectionClients.html

      - name: 9 - Gestion du statut final
        if: steps.newman.outcome == 'failure'
        run: |
          echo "Certains tests Newman ont échoué."
          exit 1
        